apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  -
    port: 80
    protocol: TCP
    targetPort: 8080
