apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: AWS_ACCOUNT_NUMBER.dkr.ecr.eu-central-1.amazonaws.com/lroos-helloworld:latest
        imagePullPolicy: Always
        name: helloworld
