---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    app: multicontainer
spec:
  containers:
  -
    name: helloworld
    imagePullPolicy: Never
    image: helloworld
    resources: {}
  -
    name: volume-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo Hello Kubernetes!  | tee -a /data/shared/producinghellos ;sleep 5; done']
    volumeMounts:
    - name: sharedstorage
      mountPath: /data/shared
  -
    name: consumer-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo "$(date) $(wc /data/shared/producinghellos) $(wget -q localhost:8080 -O-)" ;sleep 1; done']
    volumeMounts:
    - name: sharedstorage
      mountPath: /data/shared
  volumes:
  - name: sharedstorage
    emptyDir: {}  # empty dir means it will be lost on pod termination
