apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld2
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  sessionAffinity: None
  type: LoadBalancer
