apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  ports:
  -
    #nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: LoadBalancer
