apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
  -
    # nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: NodePort
