apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-pod
  name: hello-pod
spec:
  ports:
  -
    # nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-pod
  type: NodePort
