---
apiVersion: v1
kind: Service
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  selector:
    app: hello-pod
  type: NodePort
  ports:
  -
    port: 8080
    protocol: TCP
    targetPort: 8080
